[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
krunch = "4oAXoj5ztwVhuLGnNNj1PHGBwXChBFfPYid5vhyTWq5F"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/eberma/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init = "./deploy.sh && yarn run ts-mocha -p ./tsconfig.json -t 1000000 scripts/**/*.ts"
temp = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 scripts/**/*.ts"