[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
krunch = "6zYPKjtGyPSZq6pP2U9ahNZAnaTtoVK9f1BMkEL2cix5" 
# codespaces
# krunch = "6zYPKjtGyPSZq6pP2U9ahNZAnaTtoVK9f1BMkEL2cix5" 

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
# local
wallet = "/Users/mebert/.config/solana/id.json"
# codespace
# wallet = "/home/codespace/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
startValidator="yarn run ts-mocha -p ./tsconfig.json -t 1000000 scripts/**/startValidator.ts"
init = "./deploy.sh && yarn run ts-mocha -p ./tsconfig.json -t 1000000 scripts/**/init.ts"
retry = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 scripts/**/init.ts"