[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
krunch = "EnZBKfVmLQre1x8K42DJtEzNe8AbRHoWacxkLMf3fr52" 
# codespaces
# krunch = "5DLAQZJ4hPpgur3XAyot61xCHuykBeDhVVyopWtcWNkm" 

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
# local
wallet = "/Users/eberma/.config/solana/id.json"
# codespace
# wallet = "/home/codespace/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
startValidator="yarn run ts-mocha -p ./tsconfig.json -t 1000000 scripts/**/startValidator.ts"
init = "./deploy.sh && yarn run ts-mocha -p ./tsconfig.json -t 1000000 scripts/**/init.ts"
retry = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 scripts/**/init.ts"