[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
krunch = "6zYPKjtGyPSZq6pP2U9ahNZAnaTtoVK9f1BMkEL2cix5" 

[programs.devnet]
krunch = "6zYPKjtGyPSZq6pP2U9ahNZAnaTtoVK9f1BMkEL2cix5" 

[programs.mainnet]
krunch = "6zYPKjtGyPSZq6pP2U9ahNZAnaTtoVK9f1BMkEL2cix5" 

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"  # Localnet, Devnet, Mainnet
wallet = "/Users/mebert/.config/solana/id.json"
url = "https://solana-devnet.g.alchemy.com/v2/Q7iPDRrks-_ywtZnSJ9XTSBnu6QCl071"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
startValidator="yarn run ts-mocha -p ./tsconfig.json -t 1000000 scripts/**/startValidator.ts"
init = "./deploy.sh && yarn run ts-mocha -p ./tsconfig.json -t 1000000 scripts/**/init.ts"
retry = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 scripts/**/init.ts"